register:
  path: /register
  controller: App\Controller\AuthController::register
  methods: POST

bilemo:
  path: /bilemo
  controller: App\Controller\AuthController::api

login_check:
  path:     /login_check
  methods:  [POST]